apiVersion: v1
kind: PersistentVolume
metadata:
  name: adminserver-pv
  labels:
    type: registry
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:    
    server: 192.168.63.55
    path: /nfsdir/adminserver