apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: "{{ template "harbor.fullname" . }}-mysql"
  namespace: ns-harbor
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: mysql
spec:
  replicas: 1
  serviceName: "{{ template "harbor.fullname" . }}-mysql"
  selector:
    matchLabels:
{{ include "harbor.matchLabels" . | indent 6 }}
      component: mysql
  template:
    metadata:
      labels:
{{ include "harbor.labels" . | indent 8 }}
        component: mysql
    spec:
      containers:
      - name: mysql
        image: {{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}
        imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
        resources:
{{ toYaml .Values.mysql.resources | indent 10 }}
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
               name: "{{ template "harbor.fullname" . }}-mysql"
               key: mysqlRootPassword
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
          subPath: harbor-v1/mysql-data/
      {{- if not .Values.persistence.enabled }}
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc
      {{- end -}}
    